version: '3.8'

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: dsp-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
    networks:
      - dsp-network

  # MCP RAG Documentation Server
  mcp-ragdocs:
    image: node:18-alpine
    container_name: dsp-mcp-ragdocs
    restart: unless-stopped
    working_dir: /app
    command: sh -c "npm install -g @hannesrudolph/mcp-ragdocs && mcp-ragdocs"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - NODE_ENV=production
    ports:
      - "3001:3000"
    depends_on:
      - qdrant
    volumes:
      - ../docs:/app/docs:ro
    networks:
      - dsp-network

  # MCP Web Search Server
  mcp-web-search:
    image: node:18-alpine
    container_name: dsp-mcp-search
    restart: unless-stopped
    working_dir: /app
    command: sh -c "npm install -g @modelcontextprotocol/server-brave-search && mcp-server-brave-search"
    environment:
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - NODE_ENV=production
    ports:
      - "3003:3000"
    networks:
      - dsp-network

networks:
  dsp-network:
    driver: bridge
    name: dsp-network